name: Java CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  Build:
    strategy:
      matrix:
        jdkversion: [ 21 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdkversion }}
          cache: 'maven'
      - name: Build
        run: mvn -V -B clean package --file pom.xml
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Download
          path: ./target/AuthMe-*-FORK-Universal.jar
  runtime-test:
    name: Plugin Runtime Test 
    needs: [Build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - mcVersion: '1.18.2'
            javaVersion: '17'
          - mcVersion: '1.20.4'
            javaVersion: '21'
          - mcVersion: '1.21'
            javaVersion: '21'
    steps:        
      - uses: HaHaWTH/minecraft-plugin-runtime-test@paper
        with:
          server-version: ${{ matrix.mcVersion }}
          java-version: ${{ matrix.javaVersion }}
          artifact-name: Download
